### ISSUE TITLE
Error for Bruce pants 

### ISSUE THREAD

**Issue by ZoeJC** [freesewing/freesewing.org#510] opened 2020-02-16 07:50 UTC
Stack trace
TypeError: Cannot read property 'flipX' of undefined
    at https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1080137
    at n.Wp.draftBack (https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1081771)
    at n.AxEy.U.draft (https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1627009)
    at https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1484287
    at pi (https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:71206)
    at Xi (https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:79406)
    at zo (https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:117616)
    at Mu (https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:101994)
    at Nu (https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:101919)
    at ku (https://freesewing.org/commons-5d52e3a4cf5c225298d9

**Comment by joostdecock** [comment] 2020-02-16 08:06
Thanks for reporting this. Could you share your username & model this happened with, so we can reproduce this?

Tx

**Comment by ZoeJC** [comment] 2020-02-17 03:18
Hi

It's ZoeJC

And the model is James.

Zoe

**Comment by joostdecock** [comment] 2020-02-17 08:00
You should double-check the measurements for *James*, because I suspect that something went wrong with the measurements.

Their hips circumference is 144cm (56.69") which would indicate a this person is large.
But the upper leg circumference is 20cm, a value that is only realistic for babies.

So something's wrong. Please double-check your measurements, making sure to look at the documentation. 
We also include a graphical representation of the measurements to make it easier to spot mistakes.
Here is an example:

![model](https://user-images.githubusercontent.com/1708494/74634191-a8926500-5163-11ea-8601-c4153a21ed79.png)

For James, it looks like this:

![Screenshot_2020-02-17 James](https://user-images.githubusercontent.com/1708494/74634245-b9db7180-5163-11ea-9ec1-2b2e37df8ad3.png)

I'm closing this, as the issue is with the input you provide to the pattern. 
That being said, feel free to [get in touch](https://gitter.im/freesewing/help) if you need any help taking the mesaurements.

**Closed by joostdecock** 2020-02-17 08:00 UTC

**Comment by ZoeJC** [comment] 2020-02-17 09:30
Thanks

Sorry about that you are correct!

I've rechecked all the measurements and the only ones it won't accept is
waist and hip. Size 120 to 150 cm patterns are hard to come by so I was
hoping I would be able to make a larger size with this clever app. He is
not the estimate 116cm /100 cm in the waist and hips.

It's there a reason for the limit?


Thanks

Zoe

**Comment by joostdecock** [comment] 2020-02-17 10:25
There are no limits. But when proportions become unrealistic, things go off the rails.
Specifically, how can someone with a 144cm hip circumference have legs that only have 20cm circumference? That's just not possible.

So it's not that there's a limit. It's that you must have made a mistake while measuring the upper leg circumference, and now we're trying to draft a pattern for a big person with chopsticks for legs.

Please check the documentation for this measurements: https://freesewing.org/docs/measurements/upperlegcircumference/
It can't be 20cm. That's simply not possible.

**Comment by ZoeJC** [comment] 2020-02-17 10:51
Hi

Yes I said I realised I had made a mistake there.

However I still can't get it to accept that the waist is larger than 116
and I don't know why.

Zoe

**Comment by joostdecock** [comment] 2020-02-17 11:11
Sorry, I misunderstood.
There are no upper limits. Could it be that you are misreading the estimate that is also shown as the actual value?

![Screenshot_2020-02-17 James(1)](https://user-images.githubusercontent.com/1708494/74648751-92de6900-517e-11ea-878d-19010a125728.png)

The waist is currently 130cm. The estimate is 100cm, but you can safely ignore that.

**Comment by ZoeJC** [comment] 2020-02-26 10:16
Hi

Sorry to keep bothering you! I no longer seem to be able to get the pdf to
come up. I tried both on a tablet (which worked before) and a PC but the
button wouldn't generate the pattern.

ZoeJC

**Comment by joostdecock** [comment] 2020-02-26 10:26
Hmm, I need to look in to that, it's throwing an error somehow.
We're working on the save/export code, we know there's still some issues with it.

In the meanwhile, you can go to this URL: https://freesewing.org/recreate/bruce/from/dkwky/for/original

If you click export there, it will work.
You can do the same by opening your original pattern (the one that won't export), then clicking the 'recreate' button, on the page asking for measurements, click the 'clone' button, and then it will work.
(you will end up on the same URL as I posted earlier.

I've created #547 for this, as it's a more general issue

**Comment by ZoeJC** [comment] 2020-03-01 23:22
Hi

I'm just going through the sleeve instructions and got an error for the
about ease link
https://freesewing.org/en/docs/patterns/simon/options#sleevecapEase

Thanks.

Zoe

**Comment by joostdecock** [comment] 2020-03-02 08:19
Created an issue for this here: https://github.com/freesewing/freesewing.org/issues/554
