### ISSUE TITLE
Error "TypeError: undefined is not an object" with several patterns (shin, Huey, Hugo, Theo, etc.)

### ISSUE THREAD

**Issue by fmatray** [freesewing/freesewing.org#509] opened 2020-02-15 20:03 UTC
I get an error when I try to create a new "shin".

```
TypeError: undefined is not an object (evaluating 'this.config.resolvedDependencies[p][Symbol.iterator]')

LE SIGNALER SUR GITHUB
Stack trace
https://fr.freesewing.org/component---src-components-app-index-js-b0482a0c1f1ae1886111.js:1:830782
https://fr.freesewing.org/component---src-components-app-index-js-b0482a0c1f1ae1886111.js:1:821131
https://fr.freesewing.org/component---src-components-app-index-js-b0482a0c1f1ae1886111.js:1:686108
Ai@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:62194
va@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:69236
Bo@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:90752
Vo@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:87779
Vo@[native code]
Oo@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:86351
Oo@[native code]
https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:48616
https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:122751
vl@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:48563
ml@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:48498
Ro@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:85343
enqueueSetState@https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:53309
https://fr.freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:1686
https://fr.freesewing.org/app-0f58a02e0340aa900f0d.js:1:24770
```

**Comment by fmatray** [comment] 2020-02-15 20:42
I also have the same error with all top clothes (Huey, Hugo, Jaeger, etc.).
I use the model "fred" and my account is fmatray.

**Comment by joostdecock** [comment] 2020-02-16 08:08
Does the same happen on freesewing.org? (As I noticed this is from fr.freesewing.org)

**Comment by fmatray** [comment] 2020-02-16 12:20
Today , I tried again with the french version and it works now. 
I don't know what happened, I changed nothing.

**Comment by joostdecock** [comment] 2020-02-16 12:31
I was also unable to reproduce this. So I'm going to close this now, but don't hesitate to open a new issue if you run into this (or another) problem again.

**Closed by joostdecock** 2020-02-16 12:31 UTC
