### ISSUE TITLE
"Seat circumference" is missing in the german version.  (old: can't draft Theo with new model - measurement missing?)

### ISSUE THREAD

**Issue by stsydow** [freesewing/freesewing.org#235] opened 2019-10-13 22:23 UTC
I can't draft Theo with a newly created model, it lacks a measurement but I filled in everything I could. Old models from the 1.0 era work fine.

**Comment by joostdecock** [comment] 2019-10-14 06:42
Thanks for reporting this, I'll look into it.

**Comment by joostdecock** [comment] 2019-10-14 06:56
I am unable to reproduce this.
For starters, when I create a model and fill in the measurements requires for Theo (note that I'm using the pattern filter) :

![Screenshot_2019-10-14 test](https://user-images.githubusercontent.com/1708494/66733567-43023500-ee60-11e9-805a-d981c9d2f01c.png)

Then, when I select to create a new Theo pattern, this model shows up:

![Screenshot_2019-10-14 Choose a model](https://user-images.githubusercontent.com/1708494/66733586-531a1480-ee60-11e9-8819-a91d0b69053c.png)

And when I select it, it correctly drafts Theo as expected:

![Screenshot_2019-10-14 New Theo for test](https://user-images.githubusercontent.com/1708494/66733605-63ca8a80-ee60-11e9-8a73-1b70aa2bf00c.png)

So it seems to me that you might simply be missing a measurement.
Use the pattern filter on the model page to filter out the measurements required by Theo, that might help you spot the issue.

**Comment by stsydow** [comment] 2019-10-14 12:04
I found the bug: 
"Seat circumference" is missing in the german version.

I just logged in the English one and there it is.

Thanks alot for your work!
If I can help, let me know and give me a hint where to start.
I'm able to program but haven't set up the project yet.

**Comment by joostdecock** [comment] 2019-10-14 12:12
(some of) the localized versions are lagging behind the main English site because of some deploy problems.
It shouldn't happen, and this is a good reminder we should address this, so I've re-opened it.

Obviously, we'd love to have you help out. We have [a chat room for developers](https://gitter.im/freesewing/development) that is probably the best place to dip your toes in the water :)

**Comment by joostdecock** [comment] 2019-10-14 14:36
That should be fixed now, although we're having an issue with the translation: https://github.com/freesewing/freesewing.org/issues/246

So the problem should be fixed, but the site is in English now. Obviously we'll fix that ASAP.

Thanks for confirming.

**Comment by joostdecock** [comment] 2019-10-14 17:52
#246 has been fixed. That should resolve this issue. Let us know if it doesn't for some reason.

**Closed by joostdecock** 2019-10-14 17:52 UTC
