### ISSUE TITLE
Pattern Draft Wahid

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#80] opened 2019-08-30 13:04 UTC
The "Style" menu selector on "Wahid" clears the screen. The "fit" and "advanced" selectors are working fine. This is also a change in behaviour over the last couple of days.

**Comment by joostdecock** [comment] 2019-09-06 16:39
Dupe of https://github.com/freesewing/freesewing.org/issues/105

**Closed by joostdecock** 2019-09-06 16:39 UTC
