### ISSUE TITLE
ran out of path to shift along?

### ISSUE THREAD

**Issue by artairdk** [freesewing/freesewing.org#251] opened 2019-10-14 23:57 UTC
I just got this problem while trying to make the wahid pattern and i'm not sure what caused it

Error: Error in Path.shiftAlong(): Ran out of path to shift along. Distance requested was 2, path length is0.21.

Error: Error in Path.shiftAlong(): Ran out of path to shift along. Distance requested was 2, path length is0.21.
    at b.shiftAlong (https://freesewing.org/component---src-components-app-index-js-b85b25f3c6b8b420fcdb.js:1:795265)
    at https://freesewing.org/component---src-components-app-index-js-b85b25f3c6b8b420fcdb.js:1:792601
    at b.offset (https://freesewing.org/component---src-components-app-index-js-b85b25f3c6b8b420fcdb.js:1:793048)
    at n.m.draftBack (https://freesewing.org/component---src-components-app-index-js-b85b25f3c6b8b420fcdb.js:1:1473060)
    at n.Nf.draftBackBlock (https://freesewing.org/component---src-components-app-index-js-b85b25f3c6b8b420fcdb.js:1:635745)
    at n.J.draft (https://freesewing.org/component---src-components-app-index-js-b85b25f3c6b8b420fcdb.js:1:818726)
    at https://freesewing.org/component---src-components-app-index-js-b85b25f3c6b8b420fcdb.js:1:683764
    at Ai (https://freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:62193)
    at va (https://freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:69234)
    at Zo (https://freesewing.org/commons-ee1e30c54c65afff4aa1.js:1:106382)

**Comment by joostdecock** [comment] 2019-10-15 04:48
Can you let us know your username on the site and the name of the model you were using?

**Comment by artairdk** [comment] 2019-10-15 14:10
My username is Artairdk and the model is Art

**Comment by joostdecock** [comment] 2019-10-18 18:06
I have reproduced this issue. We've got 2.1.3 ready to be deployed, but I'm going to hold it back to see if we can add a fix for this to it this weekend.

**Comment by joostdecock** [comment] 2019-10-19 06:44
Your shoulder to shoulder measurement is more than half of the chest circumference. That is almost certainly incorrect. Please double-check both measurements.

That being said, the estimates for the shoulder to shoulder measurement were off, because they didn't adapt properly. That effect is most pronounced when you divert further from the base size (42).
In this case, you're closer to size 32 so the effect would have been big. That doesn't change the pattern, but the estimate might have made your think you were measuring wrong if you had a much lower value.

I've updated the estimate calculations, and they will be published today as part of v2.1.3.

But the root cause of this issue is that the measurements seem incorrect. If you disable the seam allowance, the pattern will draft, and you will see it looks wonky because there's no room to draw an armhole because the shoulder is wider than half the chest.

**Closed by joostdecock** 2019-10-19 06:44 UTC
