### ISSUE TITLE
Simon Shirt Issue

### ISSUE THREAD

**Issue by tayduffers** [freesewing/freesewing.org#417] opened 2019-12-16 01:38 UTC
When choosing a model for the Simon pattern, I receive the following page instead of a pattern. I tried with a couple other patterns but it just seems to be this one that causes any issue: 

![github](https://user-images.githubusercontent.com/58922494/70873227-c59b9380-1f7a-11ea-9032-edd352f728ee.JPG)

**Comment by joostdecock** [comment] 2019-12-16 07:33
Thanks for reporting this. This is a dupe of #416 so I will close this one and track the process there.
You can subscribe to #416 to receive updated.

**Closed by joostdecock** 2019-12-16 07:33 UTC

**Comment by joostdecock** [comment] 2019-12-16 09:27
This has been fixed :)

**Comment by tayduffers** [comment] 2019-12-16 12:31
> This has been fixed :)

I just tried it again this morning and I'm still receiving the same error 😔. Any thoughts?

**Comment by joostdecock** [comment] 2019-12-16 13:51
Can you do a hard reload (ctrl-shift reload) to make sure your browser is not using any cached code.

**Comment by joostdecock** [comment] 2019-12-17 12:47
Did you have a chance to try this?
