### ISSUE TITLE
Carlita throws an error when using seam allowance

### ISSUE THREAD

**Issue by FemNapsta** [freesewing/freesewing.org#439] opened 2020-01-07 05:07 UTC
I tried to get the Carlita pattern but it popped up with with the error message saying that it ran out of path? (I don't know what that means in the coding world).

**Comment by joostdecock** [comment] 2020-01-07 06:21
Can you share your username and model from the site so we can try to reproduce this?

Thanks

**Comment by FemNapsta** [comment] 2020-01-07 10:42
Sure thing my username is FemNapsta and my model is April

**Comment by FemNapsta** [comment] 2020-01-07 10:46
I forgot to add that there was 2 patterns the Carlita and the Wahid that had the same error message.

**Comment by joostdecock** [comment] 2020-01-07 11:37
hank you for that. I have added 4 recipes to your account: https://freesewing.org/recipes

You will find:

 - [Carlita without seam allowance](https://freesewing.org/recipes/uvpgp)
 - [Wahid without seam allowance](https://freesewing.org/recipes/qgpml)
 - [Carlita with some adjustments](https://freesewing.org/recipes/lhmpa)
 - [Wahid with some adjustments](https://freesewing.org/recipes/ggxgm)

All of these patterns draft correctly. The first two because I have disabled the seam allowance in them. The problem is triggered by the seam allowance bein offset from the seamline, so disabling seam allowance side-steps the issue.

However, the **real** issue here is the ratio between your shoulder to shoulder measurement and chest circumference.  Here's a brian drafted for model April:

![Screenshot_2020-01-07 New Brian for April](https://user-images.githubusercontent.com/1708494/71891893-e0ab8e80-3147-11ea-90c4-41300f521adc.png)

As you can see, the armholes are very shallow. This is directly caused by that ratio. Because the shoulder point and armhole pitch point are controlled by the shoulder to shoulder measurement, yet the bottom of the armhole is controlled by your chest circumference.

Since your chest circumference is less than double of the shoulder to shoulder measurement (which is uncommon, I would urge you to double-check those measurements) there is no *room* to go out again and draft a correct armhole.

The matter is worse in Wahid because it adds an additional armscye dart which it then rotates out of the way, giving you a very crooked armhole. You can see that in the no-seam-allowance version of Wahid.

What I did with the two versions that *just work* is increase the chest ease to influence the ratio between shoulder to shoulder and chest circumference. When I do that, things *just work*.

In addition, in Wahid I've reduced the armscye dart a bit to give you a smoother armhole.

Please double-check your measurements, especially your shoulder to shoulder measurement.
However, I do not think this is a bug, I just thing that as the measurements are now, you fall just outside what we can handle.

What's needed is a more graceful way to handle these outliers, but that's something we're thinking about.

Don't hesitate to get back to me if you have additional questions or input, but for now I am closing this as I consider your issue taken care of.

**Closed** 2020-01-07 11:38 UTC

**Comment by FemNapsta** [comment] 2020-01-07 15:10
Thank you so much. 😊😊
