### ISSUE TITLE
Account menu item missing

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#374] opened 2019-12-03 23:35 UTC
When I go to freesewing.org I see this:

<img width="1662" alt="FreeSewing" src="https://user-images.githubusercontent.com/209089/70098901-07c7eb00-15f3-11ea-81b8-a99d7181a3d3.png">

Then I click on the left icon (/login) and I see this:
<img width="1642" alt="Log_in" src="https://user-images.githubusercontent.com/209089/70098939-1d3d1500-15f3-11ea-8417-85192eea622e.png">

And then I click on the account button and I see this:

<img width="1638" alt="Account" src="https://user-images.githubusercontent.com/209089/70098965-2d54f480-15f3-11ea-8558-53cc9b9f0684.png">

# expected

The initial page has the account icon and links to my account

**Comment by kieranklaassen** [comment] 2019-12-03 23:35
I tried reproducing it on localhost but there it seems to work fine. Not sure whats going on here

**Comment by joostdecock** [comment] 2019-12-04 06:47
It's an SSR issue. It only happens with the server-side static page that's built by Gatsby.
When you fetch that page (initial load of the site, so typically the homepage, but you can reproduce this on any page, eg: https://freesewing.org/docs/about/faq/ ) the icon is incorrect.

Then, whenever it is re-rendered after the SPA boots (like when you click a link) it will be correct.
These SSR bugs don't show up when running the development environment, making it somewhat tricky to troubleshoot.

So well spotted, I'll have a look.

**Comment by joostdecock** [comment] 2019-12-04 06:55
This only happens when you are logged in. This is what the non-logged in user gets at initial load:

![Screenshot_2019-12-04 Log in](https://user-images.githubusercontent.com/1708494/70119660-1b169d00-166b-11ea-87c7-23097f328caa.png)

The icons and links are not only incorrect, but also mismatched when you are logged in.
The links are login / signup / patrons just as for a non-logged in user. The icons are wrong.

**Comment by joostdecock** [comment] 2019-12-04 07:00
I think the issue hinges on this line: https://github.com/freesewing/freesewing.org/blob/develop/src/components/app/navbar.js#L81

```js
  if (props.app.account.username) {
    delete navs.right.login
    delete navs.right.signup
  } else {
    delete navs.right.create
    delete navs.right.account
  }
```

On server-side render, `props.app.account.username` is never going to have a value. So we always end up removing the `create` and `account` links from the navbar.

Then, at some point, the client-side render kicks in and gets it wrong.
You can actually see that while the page is loading (spinning logo) the navbar looks like in the screenshot above (for a non-logged in user). Then when loading is complete, it triggers a re-render, but gets it wrong somehow.

I'll have to look deeper into it to understand how this re-render gets it wrong somehow, but my train is about to arrive :)

**Comment by joostdecock** [comment] 2020-02-20 15:06
I'm closing this as the 2.2 menu is different, so this particular issue is no longer relevant

**Closed by joostdecock** 2020-02-20 15:06 UTC
Labels: bug
