### ISSUE TITLE
Pattern Draft:Simon

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#76] opened 2019-08-29 10:39 UTC
The "Style" menu selector on Simon clears the screen. The "fit" and "advanced" selectors are working fine.  This is a change in behaviour over the last couple of days.

**Comment by joostdecock** [comment] 2019-09-06 16:10
Dupe of https://github.com/freesewing/freesewing.org/issues/105 which has been fixed (but not deployed yet)

**Closed by joostdecock** 2019-09-06 16:10 UTC
Labels: bug
