### ISSUE TITLE
Error when generating Breanna pattern from measurements

### ISSUE THREAD

**Issue by readling** [freesewing/freesewing.org#692] opened 2020-05-13 22:24 UTC
Tried to generate new Breanna pattern from measurements, and got the following error.

Stack Trace: 
TypeError: o.scyeDart1.shiftTowards is not a function
    at o.S.draftFrontBase (https://freesewing.org/component---src-pages-patterns-pattern-index-js-60af9f5d7071a2661fdf.js:1:35180)
    at o.AxEy.V.draft (https://freesewing.org/component---src-pages-patterns-pattern-index-js-60af9f5d7071a2661fdf.js:1:662034)
    at e.a (https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:1073231)
    at Ki (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:70048)
    at Fa (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:78909)
    at vo (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:117457)
    at cu (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108782)
    at ou (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108707)
    at Zo (https://freesewing.org/framework-5a7bf077542a910ca662.js:1:105788)
    at https://freesewing.org/framework-5a7bf077542a910ca662.js:1:57450

![breanna-error](https://user-images.githubusercontent.com/65316090/81872033-fe01c680-9546-11ea-9998-223de0c63942.PNG)

**Comment by joostdecock** [comment] 2020-05-15 14:13
Dupe of #688

**Closed by joostdecock** 2020-05-15 14:13 UTC
