### ISSUE TITLE
Error when trying to draft Breanna paperless

### ISSUE THREAD

**Issue by AlfaLyr** [freesewing/freesewing.org#548] opened 2020-02-27 12:17 UTC
ReferenceError: y is not defined
    at o.T.draftBack (https://freesewing.org/component---src-pages-create-design-for-person-js-8211d717b3e960968771.js:1:32125)
    at o.AxEy.U.draft (https://freesewing.org/component---src-pages-create-design-for-person-js-8211d717b3e960968771.js:1:686775)
    at e.a (https://freesewing.org/component---src-pages-create-design-for-person-js-8211d717b3e960968771.js:1:1476450)
    at ci (https://freesewing.org/commons-ced7d089c4de5c5845b8.js:1:676127)
    at Yi (https://freesewing.org/commons-ced7d089c4de5c5845b8.js:1:684349)
    at Ts (https://freesewing.org/commons-ced7d089c4de5c5845b8.js:1:722388)
    at hl (https://freesewing.org/commons-ced7d089c4de5c5845b8.js:1:706813)
    at fl (https://freesewing.org/commons-ced7d089c4de5c5845b8.js:1:706738)
    at al (https://freesewing.org/commons-ced7d089c4de5c5845b8.js:1:704086)
    at https://freesewing.org/commons-ced7d089c4de5c5845b8.js:1:662528

**Comment by joostdecock** [comment] 2020-03-04 18:01
I am unable to reproduce this. Could you tell me how you ended up with this error?

**Comment by AlfaLyr** [comment] 2020-03-05 07:30
I can't reproduce it anymore, I don't know what happened before :S

**Comment by joostdecock** [comment] 2020-03-05 07:40
Ok, then I'll close this and if it ever resurfaces, we'll delve into it at that time 🙂

**Closed by joostdecock** 2020-03-05 07:40 UTC
Labels: bug, pkg:breanna
