### ISSUE TITLE
"Export for editing" to pdf/svg doesn't correctly place measurements

### ISSUE THREAD

**Issue by woolishboy** [freesewing/freesewing.org#315] opened 2019-11-15 22:54 UTC
It appears as if all of the measurements for each "panel" have the same coordinates and aren't positioned correctly on the pattern.
![image](https://user-images.githubusercontent.com/57816321/68981089-f47de880-07c7-11ea-81ce-02b605643ebe.png)

**Comment by joostdecock** [comment] 2019-11-16 07:59
Did/Do they show correctly in the browser, as in, is this issue specific to the svg/pdf export?

**Comment by joostdecock** [comment] 2019-11-16 09:42
Here's a (screenshot of) a PDF export:

![Screenshot_2019-11-16 pattern-full pdf](https://user-images.githubusercontent.com/1708494/68991295-81bf4c80-085d-11ea-98b6-69c72bacfca8.png)

And here's a (screenshot of) an SVG export:
![Screenshot from 2019-11-16 10-39-55](https://user-images.githubusercontent.com/1708494/68991296-84ba3d00-085d-11ea-9e67-02a8dba2915a.png)

As you can see, I can't reproduce the issue you reported. Could you tell me what pattern it is, as perhaps it's something pattern specific.

**Comment by woolishboy** [comment] 2019-11-17 19:02
Ok, I found another clue. It only seems to occur when the units are set to inches. I originally noticed it on Brian, but I tested on Wahid and Theo, too, with the same results. So it doesn't look like it's a bug in a particular pattern. If I show Expert mode, switch units to cm, then export to PDF it places the measurements correctly. Also, the measurements are located correctly in the SVG pattern display in the browser - the issue only happens in exported files (both SVG and PDF).

**Comment by joostdecock** [comment] 2019-11-18 07:47
Hmm, that's strange indeed. Good investigative work though. This should allow us to zoom in to the issue.

**Comment by joostdecock** [comment] 2019-11-19 17:40
Fixed in the develop branch. This was due to the `"` sign for inch not being properly escaped, and thus breaking the SVG tag.

WIll be included in 2.4.5 which should be rolled out this week.

**Closed by joostdecock** 2019-11-19 17:40 UTC
Labels: bug

**Comment by joostdecock** [comment] 2019-11-19 18:39
It's been deployed on freesewing.org now :)
