### ISSUE TITLE
Error page when clicking on Breanna Body Block

### ISSUE THREAD

**Issue by ThatsspMaeven** [freesewing/freesewing.org#691] opened 2020-05-12 17:51 UTC
I get this error when clicking on the breanna body 

TypeError: o.scyeDart1.shiftTowards is not a function. (In 'o.scyeDart1.shiftTowards(o.bustPoint,w)', 'o.scyeDart1.shiftTowards' is undefined)

Stacktrace:
https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:35234
https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:656202
https://freesewing.org/component---src-pages-create-design-for-person-js-8d27888b7fdaab612c95.js:1:1073236
Ki@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:70049
Fa@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:78911
cu@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108784
ou@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:108709
Zo@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:105790
Zo@[native code]
https://freesewing.org/framework-5a7bf077542a910ca662.js:1:57451
https://freesewing.org/framework-5a7bf077542a910ca662.js:1:4697
Hl@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:57397
Bl@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:57332
qo@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:102575
enqueueSetState@https://freesewing.org/framework-5a7bf077542a910ca662.js:1:61117
https://freesewing.org/framework-5a7bf077542a910ca662.js:1:7190
https://freesewing.org/app-1c62fcd7383f866a2290.js:1:213884
https://freesewing.org/commons-bc4c0309728060287b18.js:1:57691

**Comment by joostdecock** [comment] 2020-05-15 14:13
Dupe of #688

**Closed by joostdecock** 2020-05-15 14:13 UTC
